[ui.window.box.scroll.list]
max_height = 450
max_width = 500
min_width = 500
width = 500

[ui.window.box]
width = 500


[shell]
anchor_top = false
anchor_bottom = true
anchor_left = false
anchor_right = true
