debug = true
force_keyboard_focus = true
hotreload_theme = true
theme = "default"
timeout = 60

[keybinds]
next = ["Tab"]
previous = ["shift ISO_Left_Tab"]

[providers]
default = ["desktopapplications", "calc", "menus", "websearch"]
