# fast left click for Path of Exile
bindn = ctrl, mouse_down, exec, ydotool click C0
bindn = ctrl, mouse_up, exec, ydotool click C0

bindn = ctrl shift, mouse_down, exec, ydotool click C0
bindn = ctrl shift, mouse_up, exec, ydotool click C0
#
# bindn = , F2, exec, ~/.config/dotfiles/scripts/path-of-exile/poe_enter.sh
# bindn = , F4, exec, ~/.config/dotfiles/scripts/path-of-exile/poe_type.sh /exit
bindn = , F4, exec, ~/.config/dotfiles/scripts/path-of-exile/poe_type.sh /menagerie
bindn = , F5, exec, ~/.config/dotfiles/scripts/path-of-exile/poe_type.sh /hideout
bindn = , F6, exec, ~/.config/dotfiles/scripts/path-of-exile/poe_type.sh /kingsmarch
bindn = , F7, exec, ~/.config/dotfiles/scripts/path-of-exile/poe_type.sh /monastery
