layerrule = blur, waybar
layerrule = blur, swaync-control-center
layerrule = ignorealpha 0.1, swaync-control-center 
layerrule = blur, swaync-notification-window
layerrule = ignorealpha 0.1, swaync-notification-window
layerrule = blur, quickshell
layerrule = blur, swayosd
layerrule = blur, rofi
layerrule = blur, walker
layerrule = ignorealpha 0.2, walker
layerrule = ignorealpha 0.1, swayosd
layerrule = noanim, walker

windowrule = float, class:steam
windowrule = center, class:steam, title:Steam
windowrule = opacity 1 1, class:steam
windowrule = size 1100 700, class:steam, title:Steam
windowrule = size 460 800, class:steam, title:Friends List

windowrulev2 = suppressevent maximize, class:.*

windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


 windowrulev2 = float, class:^(pavucontrol)$
    windowrulev2 = size 600 400, class:^(pavucontrol)$
    windowrulev2 = center, class:^(pavucontrol)$



# Float, borderless
windowrulev2 = float, class:^(awakened-poe-trade)$
windowrulev2 = noborder, class:^(awakened-poe-trade)$
windowrulev2 = nofocus, class:^(awakened-poe-trade)$
windowrulev2 = noblur, class:^(awakened-poe-trade)$

# layerrule=noanim, rofi

windowrule = size 800 600, title:^(Wiremix|Impala|Network Manager)$
windowrule = float, title:^(Wiremix|Btop|Impala|Image Resizer|Network Manager)$
windowrule = center, title:^(Wiremix|Btop|Impala|Image Resizer|Network Manager)$
windowrule = float, class:^(Btop)


windowrulev2 = float, class:^(blueberry.py|Bitwarden|signal|org.gnome.Calendar|spotify|discord|xdg-desktop-portal-gtk|eog|org.gnome.Evince)$
windowrulev2 = center, class:^(blueberry.py|Bitwarden|signal|org.gnome.Calendar|spotify|discord|xdg-desktop-portal-gtk|eog|org.gnome.Evince)$
windowrulev2 = size 800 600, class:^(blueberry.py|org.gnome.Calendar)$

windowrulev2 = size 1000 600, class:^(Bitwarden)$
windowrulev2 = size 1400 800, class:^(spotify|legcord|signal|xdg-desktop-portal-gtk|eog|Btop)$
windowrulev2 = size 800 950, class:^(org.gnome.Evince)
windowrulev2 = fullscreen, class:^(com.moonlight_stream.Moonlight)

# in hyprland.conf
# windowrulev2 = float,class:^(Rofi)$
# windowrulev2 = pin,class:^(Rofi)$
windowrulev2 = stayfocused,class:^(Rofi)$

windowrulev2 = tile, class:^(steam_app_238960)
